# Preview of sample data

+ Problems: TSP, CVRP, SDVRP, OP (distance-based), PCTSP (deterministic)
+ Each dataset contains 15 samples, each with batch size 1
+ Each sample contains solution and cost obtained by AM-90epochs

In [2]:
import pickle
import numpy as np
from glob import glob

In [3]:
folder = "sample_data"
sorted(glob("{}/*.pkl".format(folder)))

['sample_data/cvrp100.pkl',
 'sample_data/cvrp20.pkl',
 'sample_data/cvrp50.pkl',
 'sample_data/op100_dist.pkl',
 'sample_data/op20_dist.pkl',
 'sample_data/op50_dist.pkl',
 'sample_data/pctsp100_det.pkl',
 'sample_data/pctsp20_det.pkl',
 'sample_data/pctsp50_det.pkl',
 'sample_data/sdvrp100.pkl',
 'sample_data/sdvrp20.pkl',
 'sample_data/sdvrp50.pkl',
 'sample_data/tsp100.pkl',
 'sample_data/tsp20.pkl',
 'sample_data/tsp50.pkl']

In [4]:
def load_sample_data(loadpath):
    with open(loadpath, 'rb') as f:
        return pickle.load(f)

---

## 1. TSP

In [8]:
graph_size = 20 # 20/50/100
loadpath = "{}/tsp{}.pkl".format(folder, graph_size)
sample_data = load_sample_data(loadpath)
print(len(sample_data))
single_data = sample_data[0]
print(single_data.keys())
print("===== ===== =====")
for key in single_data.keys():
    print(key)
    value = single_data[key]
    print(value.shape, value.dtype)
    print(single_data[key])
    print("---------- -----")

15
dict_keys(['loc', 'solution', 'cost'])
===== ===== =====
loc
(1, 20, 2) float32
[[[0.02897924 0.40189856]
  [0.25984418 0.36664134]
  [0.05830073 0.70064473]
  [0.05179739 0.46813923]
  [0.67380613 0.33146197]
  [0.78370804 0.5630632 ]
  [0.7748505  0.82080257]
  [0.27927655 0.6817111 ]
  [0.28367496 0.6567304 ]
  [0.23875582 0.7312845 ]
  [0.60122263 0.30432844]
  [0.25475216 0.62936187]
  [0.9665111  0.7399492 ]
  [0.4517179  0.47573084]
  [0.78419435 0.15249622]
  [0.6662244  0.33432305]
  [0.7892904  0.32163972]
  [0.52472377 0.6688407 ]
  [0.8436147  0.4265083 ]
  [0.9561459  0.07697695]]]
---------- -----
solution
(1, 20) int64
[[19 16 18  5 12  6 17  8 11  7  9  2  3  0  1 13 10 15  4 14]]
---------- -----
cost
(1,) float32
[3.366598]
---------- -----


----

## CVRP

In [9]:
graph_size = 20 # 20/50/100
loadpath = "{}/cvrp{}.pkl".format(folder, graph_size)
sample_data = load_sample_data(loadpath)
print(len(sample_data))
single_data = sample_data[0]
print(single_data.keys())
print("===== ===== =====")
for key in single_data.keys():
    print(key)
    value = single_data[key]
    print(value.shape, value.dtype)
    print(single_data[key])
    print("---------- -----")

15
dict_keys(['loc', 'demand', 'depot', 'solution', 'cost'])
===== ===== =====
loc
(1, 20, 2) float32
[[[0.02897924 0.40189856]
  [0.25984418 0.36664134]
  [0.05830073 0.70064473]
  [0.05179739 0.46813923]
  [0.67380613 0.33146197]
  [0.78370804 0.5630632 ]
  [0.7748505  0.82080257]
  [0.27927655 0.6817111 ]
  [0.28367496 0.6567304 ]
  [0.23875582 0.7312845 ]
  [0.60122263 0.30432844]
  [0.25475216 0.62936187]
  [0.9665111  0.7399492 ]
  [0.4517179  0.47573084]
  [0.78419435 0.15249622]
  [0.6662244  0.33432305]
  [0.7892904  0.32163972]
  [0.52472377 0.6688407 ]
  [0.8436147  0.4265083 ]
  [0.9561459  0.07697695]]]
---------- -----
demand
(1, 20) float32
[[0.13333334 0.03333334 0.16666667 0.2        0.1        0.23333333
  0.13333334 0.03333334 0.26666668 0.26666668 0.23333333 0.3
  0.23333333 0.23333333 0.3        0.13333334 0.03333334 0.1
  0.13333334 0.16666667]]
---------- -----
depot
(1, 2) float32
[[0.49661124 0.7865359 ]]
---------- -----
solution
(1, 23) int64
[[ 7 13  6 19  0

---

## 3. SDVRP

In [10]:
graph_size = 20 # 20/50/100
loadpath = "{}/sdvrp{}.pkl".format(folder, graph_size)
sample_data = load_sample_data(loadpath)
print(len(sample_data))
single_data = sample_data[0]
print(single_data.keys())
print("===== ===== =====")
for key in single_data.keys():
    print(key)
    value = single_data[key]
    print(value.shape, value.dtype)
    print(single_data[key])
    print("---------- -----")

15
dict_keys(['loc', 'demand', 'depot', 'solution', 'cost'])
===== ===== =====
loc
(1, 20, 2) float32
[[[0.02897924 0.40189856]
  [0.25984418 0.36664134]
  [0.05830073 0.70064473]
  [0.05179739 0.46813923]
  [0.67380613 0.33146197]
  [0.78370804 0.5630632 ]
  [0.7748505  0.82080257]
  [0.27927655 0.6817111 ]
  [0.28367496 0.6567304 ]
  [0.23875582 0.7312845 ]
  [0.60122263 0.30432844]
  [0.25475216 0.62936187]
  [0.9665111  0.7399492 ]
  [0.4517179  0.47573084]
  [0.78419435 0.15249622]
  [0.6662244  0.33432305]
  [0.7892904  0.32163972]
  [0.52472377 0.6688407 ]
  [0.8436147  0.4265083 ]
  [0.9561459  0.07697695]]]
---------- -----
demand
(1, 20) float32
[[0.13333334 0.03333334 0.16666667 0.2        0.1        0.23333333
  0.13333334 0.03333334 0.26666668 0.26666668 0.23333333 0.3
  0.23333333 0.23333333 0.3        0.13333334 0.03333334 0.1
  0.13333334 0.16666667]]
---------- -----
depot
(1, 2) float32
[[0.49661124 0.7865359 ]]
---------- -----
solution
(1, 23) int64
[[ 7 13  6 19 18

---

## OP (distance)

In [11]:
graph_size = 20 # 20/50/100
loadpath = "{}/op{}_dist.pkl".format(folder, graph_size)
sample_data = load_sample_data(loadpath)
print(len(sample_data))
single_data = sample_data[0]
print(single_data.keys())
print("===== ===== =====")
for key in single_data.keys():
    print(key)
    value = single_data[key]
    print(value.shape, value.dtype)
    print(single_data[key])
    print("---------- -----")

15
dict_keys(['loc', 'prize', 'depot', 'max_length', 'solution', 'cost'])
===== ===== =====
loc
(1, 20, 2) float32
[[[0.02897924 0.40189856]
  [0.25984418 0.36664134]
  [0.05830073 0.70064473]
  [0.05179739 0.46813923]
  [0.67380613 0.33146197]
  [0.78370804 0.5630632 ]
  [0.7748505  0.82080257]
  [0.27927655 0.6817111 ]
  [0.28367496 0.6567304 ]
  [0.23875582 0.7312845 ]
  [0.60122263 0.30432844]
  [0.25475216 0.62936187]
  [0.9665111  0.7399492 ]
  [0.4517179  0.47573084]
  [0.78419435 0.15249622]
  [0.6662244  0.33432305]
  [0.7892904  0.32163972]
  [0.52472377 0.6688407 ]
  [0.8436147  0.4265083 ]
  [0.9561459  0.07697695]]]
---------- -----
prize
(1, 20) float32
[[0.6  0.43 0.84 0.64 0.46 0.73 0.97 0.75 0.72 0.81 0.39 0.7  1.   0.51
  0.44 0.45 0.54 0.73 0.65 0.59]]
---------- -----
depot
(1, 2) float32
[[0.4108109  0.00141209]]
---------- -----
max_length
(1,) float32
[2.]
---------- -----
solution
(1, 10) int64
[[11 16  5 14  9  8 10 12  4  0]]
---------- -----
cost
(1,) float32

----

## 5. PCTSP (deterministic)

In [12]:
graph_size = 20 # 20/50/100
loadpath = "{}/pctsp{}_det.pkl".format(folder, graph_size)
sample_data = load_sample_data(loadpath)
print(len(sample_data))
single_data = sample_data[0]
print(single_data.keys())
print("===== ===== =====")
for key in single_data.keys():
    print(key)
    value = single_data[key]
    print(value.shape, value.dtype)
    print(single_data[key])
    print("---------- -----")

15
dict_keys(['depot', 'loc', 'penalty', 'deterministic_prize', 'stochastic_prize', 'solution', 'cost'])
===== ===== =====
depot
(1, 2) float32
[[0.02897924 0.40189856]]
---------- -----
loc
(1, 20, 2) float32
[[[0.25984418 0.36664134]
  [0.05830073 0.70064473]
  [0.05179739 0.46813923]
  [0.67380613 0.33146197]
  [0.78370804 0.5630632 ]
  [0.7748505  0.82080257]
  [0.27927655 0.6817111 ]
  [0.28367496 0.6567304 ]
  [0.23875582 0.7312845 ]
  [0.60122263 0.30432844]
  [0.25475216 0.62936187]
  [0.9665111  0.7399492 ]
  [0.4517179  0.47573084]
  [0.78419435 0.15249622]
  [0.6662244  0.33432305]
  [0.7892904  0.32163972]
  [0.52472377 0.6688407 ]
  [0.8436147  0.4265083 ]
  [0.9561459  0.07697695]
  [0.4108109  0.00141209]]]
---------- -----
penalty
(1, 20) float32
[[0.162426   0.19256704 0.089279   0.2122985  0.12568365 0.01965183
  0.26515996 0.24248451 0.22584116 0.26964933 0.20515801 0.22975351
  0.274475   0.1197776  0.03301417 0.07623115 0.1299764  0.13351701
  0.14898337 0.23596078